const express = require('express')
const cors = require('cors')
const bodyParser = require('body-parser')
require('dotenv').config()
const authRoutes = require('./routes/auth')
const userRoutes = require('./routes/users')
const equipmentRoutes = require('./routes/equipment')
const partsRoutes = require('./routes/parts')
const routesRoutes = require('./routes/routes')
const operationsRoutes = require('./routes/operations')
const app = express()
app.use(cors())
app.use(bodyParser.json())
app.use('/auth', authRoutes)
app.use('/users', userRoutes)
app.use('/equipment', equipmentRoutes)
app.use('/parts', partsRoutes)
app.use('/routes', routesRoutes)
app.use('/operations', operationsRoutes)
app.get('/', (req, res) => {
  res.send('SEMZ AIS Backend is running')
})
app.use((err, req, res, next) => {
  res.status(500).json({ error: 'Internal server error' })
})
module.exports = app
